apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-liberty-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: open-liberty-operator
  template:
    metadata:
      labels:
        name: open-liberty-operator
    spec:
      serviceAccountName: open-liberty-operator
      containers:
        - name: open-liberty-operator
          image: openliberty/operator:daily
          command:
          - open-liberty-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "open-liberty-operator"
