apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .cv.release }}-liberty-logs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: {{ .cv.nfs.path }}
    server: {{ .cv.nfs.server }}